# Validates the semantic release title for PRs
# https://github.com/marketplace/actions/semantic-pull-request
name: PR Title Check for Semantic Release

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, converted_to_draft, ready_for_review]

jobs:
  main:
    name: Validate Semantic Release PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
